# Generated by Django 3.2.6 on 2022-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='url',
            field=models.TextField(max_length=300),
        ),
    ]
