# Generated by Django 3.2.6 on 2022-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_broadcast_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
