# Generated by Django 4.1.1 on 2022-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0004_news_playerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
