# Generated by Django 3.2.6 on 2022-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
